AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure pour la Zone ERP - ProjetDeFous

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Type d'instance EC2
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: AurelienClef
    Description: Nom de la paire de clés pour accéder à l'instance EC2
  DomainName:
    Type: String
    Default: e5estiam.com
    Description: Nom de domaine principal géré par Route 53
  SubDomain:
    Type: String
    Default: prodefous-vitrine
    Description: Sous-domaine à configurer pour le site vitrine

Resources:
  ### VPC et Réseau ###
  ProjetDeFousVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ProjetDeFousVPC

  ProjetDeFousPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProjetDeFousVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  ProjetDeFousPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProjetDeFousVPC
      CidrBlock: 10.0.2.0/24

  ProjetDeFousInternetGateway:
    Type: AWS::EC2::InternetGateway

  ProjetDeFousAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ProjetDeFousVPC
      InternetGatewayId: !Ref ProjetDeFousInternetGateway

  ProjetDeFousRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProjetDeFousVPC

  ProjetDeFousRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ProjetDeFousRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref ProjetDeFousInternetGateway

  ProjetDeFousPublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ProjetDeFousPublicSubnet
      RouteTableId: !Ref ProjetDeFousRouteTable

  ### Instances EC2 - Zone ERP ###

  # 1) Base de données MySQL dans le sous-réseau privé
  ProjetDeFousERPDBInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-09042b2f6d07d164a
      SubnetId: !Ref ProjetDeFousPrivateSubnet
      Tags:
        - Key: Name
          Value: ProjetDeFousERP-MySQL-DB

  # 2) Instance Front/Back dans le sous-réseau public
  ProjetDeFousERPFrontBackInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-09042b2f6d07d164a
      SubnetId: !Ref ProjetDeFousPublicSubnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: ProjetDeFousERP-FrontBack
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # MàJ du système
          sudo apt-get update -y
          sudo apt-get upgrade -y

          # Installation de MySQL
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql

          # Création base de données, utilisateur et mot de passe
          sudo mysql -e "CREATE DATABASE myappdb;"
          sudo mysql -e "CREATE USER 'myappuser'@'localhost' IDENTIFIED BY 'rK7r6d63Mbj7EH';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON myappdb.* TO 'myappuser'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

          # Installation de Git
          sudo apt-get install -y git

          # Installation de Java 17 et Maven
          sudo apt-get install -y openjdk-17-jdk maven

          # Cloner et builder l'appli Spring Boot
          git clone https://github.com/CLSigmaaa/AWS-ERP-FORK.git /home/ubuntu/spring-app
          cd /home/ubuntu/spring-app
          mvn clean install
          # Lancement de l'appli en arrière-plan
          java -jar target/spring-boot-app-0.0.1-SNAPSHOT.jar &

          # Installation Node.js (version 18), Yarn, PM2
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g yarn pm2

          # Cloner une app Next.js et la lancer
          git clone https://github.com/vercel/nextjs-postgres-nextauth-tailwindcss-template.git /home/ubuntu/nextjs-app
          cd /home/ubuntu/nextjs-app
          yarn install
          yarn build
          pm2 start "yarn start" --name "nextjs-app" --watch
          pm2 save

          # Configuration pare-feu (UFW)
          sudo ufw allow 22             # SSH
          sudo ufw allow 3306           # MySQL
          sudo ufw allow 8080           # Spring Boot
          sudo ufw allow 3000           # Next.js
          sudo ufw --force enable

  # Instances DB et test supplémentaires (si besoin)
  ProjetDeFousERPDBTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-09042b2f6d07d164a
      SubnetId: !Ref ProjetDeFousPrivateSubnet
      Tags:
        - Key: Name
          Value: ProjetDeFousERP-DB-Test

  ProjetDeFousERPTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-09042b2f6d07d164a
      SubnetId: !Ref ProjetDeFousPublicSubnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: ProjetDeFousERP-Test

  ###### SecurityGroup ######
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for ERP front/back SSH access"
      VpcId: !Ref ProjetDeFousVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0   # SSH
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0   # MySQL
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0   # Spring Boot
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0   # Next.js

Outputs:
  ProjetDeFousERPInstances:
    Description: Liste des instances EC2 pour la Zone ERP
    Value: |
      ERP-MySQL-DB: !Ref ProjetDeFousERPDBInstance
      ERP-FrontBack: !Ref ProjetDeFousERPFrontBackInstance
      ERP-DB-Test: !Ref ProjetDeFousERPDBTestInstance
      ERP-Test: !Ref ProjetDeFousERPTestInstance
